---
title: "R Notebook"
output: html_notebook
---



```{r}
source("2_7_21_Update/LeadingIndicatorToolsVS_v2.R")
library("covidcast")
library(tidyr)
library(dplyr)
drs_visits_prepared_fall = get_and_parse_signals("2020-09-01", "2020-11-30", "doctor-visits", "smoothed_adj_cli", 2000, 80)
```

```{r}
drs_visits_prepared_summer = get_and_parse_signals("2020-06-01", "2020-8-31", "doctor-visits", "smoothed_adj_cli", 2000, 80)
```

```{r}
drs_visits_prepared_all_time = get_and_parse_signals("2020-06-01", "2020-12-31", "doctor-visits", "smoothed_adj_cli", 4000, 160)

```
```{r}
drs_visits_prepared_nov = get_and_parse_signals("2020-06-01", "2020-11-30", "doctor-visits", "smoothed_adj_cli", 4000, 160)

```


```{r}
change_healthcare_prepared_fall = get_and_parse_signals("2020-09-01", "2020-11-30", "chng", "smoothed_adj_outpatient_cli", 2000, 80)
```

```{r}
change_healthcare_prepared_summer = get_and_parse_signals("2020-06-01", "2020-08-31", "chng", "smoothed_adj_outpatient_cli", 2000, 80)
```



```{r}
fb_cli_prepared_fall = get_and_parse_signals("2020-09-01", "2020-11-30", "fb-survey", "smoothed_wcli", 2000, 80)
```

```{r}
fb_cli_prepared_summer = get_and_parse_signals("2020-06-01", "2020-08-31", "fb-survey", "smoothed_wcli", 2000, 80)
```

```{r}
# Get the increase points for all the indicator and case signals
drs_fall = get_increase_points(drs_visits_prepared_fall$cases, drs_visits_prepared_fall$indicator)
drs_summer = get_increase_points(drs_visits_prepared_summer$cases, drs_visits_prepared_summer$indicator)
drs_all_time = get_increase_points(drs_visits_prepared_all_time$cases, drs_visits_prepared_all_time$indicator)
drs_nov = get_increase_points(drs_visits_prepared_nov$cases, drs_visits_prepared_nov$indicator)

chng_fall = get_increase_points(change_healthcare_prepared_fall$cases, change_healthcare_prepared_fall$indicator)
chng_summer = get_increase_points(change_healthcare_prepared_summer$cases, change_healthcare_prepared_summer$indicator)

fb_fall = get_increase_points(fb_cli_prepared_fall$cases, fb_cli_prepared_fall$indicator)
fb_summer = get_increase_points(fb_cli_prepared_summer$cases, fb_cli_prepared_summer$indicator)

```

```{r}
source("LeadingIndicatorTools.R")

drs_fall = get_increase_points(drs_visits_prepared_fall$cases, drs_visits_prepared_fall$indicator)

print(drs_fall[[1]])
print(drs_fall[[2]])
print(drs_fall[[3]])
print(drs_fall[[4]])
print(drs_fall[[5]])
print(drs_fall[[6]])
print(drs_fall[[7]])
print(drs_fall[[20]])
print(drs_fall[[30]])
print(drs_fall[[40]])
print(drs_fall[[50]])
print(drs_fall[[60]])
print(drs_fall[[70]])
print(drs_fall[[80]])
print(drs_fall[[90]])
print(drs_fall[[100]])
print(drs_fall[[120]])
print(drs_fall[[130]])
print(drs_fall[[110]])
print(drs_fall[[150]])
print(drs_fall[[160]])
print(drs_fall[[170]])
print(drs_fall[[180]])
print(drs_fall[[190]])
print(drs_fall[[200]])
print(drs_fall[[210]])

print(fb_fall[[200]])
print(fb_fall[[300]])
print(fb_fall[[330]])
print(fb_fall[[340]])
print(fb_fall[[350]])
print(fb_fall[[370]])
print(fb_fall[[380]])
print(fb_fall[[210]])
print(fb_fall[[310]])
print(fb_fall[[320]])






# print(drs_summer[[50]])
# print(chng_fall[[100]])
# print(chng_summer[[150]])
# print(fb_fall[[100]])
# print(fb_summer[[150]])


```


```{r}
source("LeadingIndicatorTools.R")

drs_fall = get_increase_points(drs_visits_prepared_fall$cases, drs_visits_prepared_fall$indicator)
chng_fall = get_increase_points(change_healthcare_prepared_fall$cases, change_healthcare_prepared_fall$indicator)
chng_summer = get_increase_points(change_healthcare_prepared_summer$cases, change_healthcare_prepared_summer$indicator)
fb_fall = get_increase_points(fb_cli_prepared_fall$cases, fb_cli_prepared_fall$indicator)

plot_signals(fb_fall, "06097", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "01003", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "55073", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "53011", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "48439", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "01073", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "48167", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "48027", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "42095", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "12086", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "12031", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "10005", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "08101", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "08001", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "06059", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "06007", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "30063", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "18127", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "46103", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "45015", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "34003", smooth_and_show_increase_point=TRUE, "FB CLI")
# plot_signals(fb_fall, "17093", smooth_and_show_increase_point=TRUE, "FB CLI")
# plot_signals(fb_fall, "17027", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "12095", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "13089", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "12117", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "12053", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "12001", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "09001", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "08013", smooth_and_show_increase_point=TRUE, "FB CLI")
plot_signals(fb_fall, "06087", smooth_and_show_increase_point=TRUE, "FB CLI")


plot_signals(drs_fall, "39011", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "06097", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "01003", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "01043", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "01015", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "01069", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "01073", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "01077", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "04005", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "05033", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "12086", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "12031", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "10005", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "08101", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "08001", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "06059", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "06007", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "19049", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "18127", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "18063", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "17199", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "17141", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "17093", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "17027", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "12095", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "13089", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "12117", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "12053", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "12001", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "09001", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "08013", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(drs_fall, "06087", smooth_and_show_increase_point=TRUE, "Dr visits")


plot_signals(chng_fall, "06097", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "01003", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "01043", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "01015", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "01069", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "01073", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "01077", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "04005", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "05033", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "12086", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "12031", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "10005", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "08101", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "08001", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "06059", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "06007", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "19049", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "18127", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "18063", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "17199", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "17141", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "17093", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "17027", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "12095", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "13089", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "12117", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "12053", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "12001", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "09001", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "08013", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_fall, "06087", smooth_and_show_increase_point=TRUE, "Change Healthcare")


plot_signals(chng_summer, "06097", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "01003", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "01043", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "01015", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "01069", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "01073", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "01077", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "04005", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "05033", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "12086", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "12031", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "10005", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "08101", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "08001", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "06059", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "06007", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "19049", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "18127", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "18063", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "17199", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "17141", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "17093", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "17027", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "12095", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "13089", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "12117", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "12053", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "12001", smooth_and_show_increase_point=TRUE, "Change Healthcare")
plot_signals(chng_summer, "09001", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "08013", smooth_and_show_increase_point=TRUE, "Change Healthcare")
# plot_signals(chng_summer, "06087", smooth_and_show_increase_point=TRUE, "Change Healthcare")





```

```{r}
# Find counties where multiple signals do well over multiple time periods
success_examples_drs_fall = get_success_examples(drs_fall, success_window_max = 14, success_window_min = 3)
success_examples_drs_summer = get_success_examples(drs_summer, success_window_max = 14, success_window_min = 3)
success_examples_drs_all_time = get_success_examples(drs_all_time, success_window_max = 21, success_window_min = 2)
success_examples_drs_nov = get_success_examples(drs_nov, success_window_max = 14, success_window_min = 3)


success_examples_chng_fall = get_success_examples(chng_fall, success_window_max = 14, success_window_min = 3)
success_examples_chng_summer = get_success_examples(chng_summer, success_window_max = 14, success_window_min = 3)

success_examples_fb_fall = get_success_examples(fb_fall, success_window_max = 14, success_window_min = 3)
success_examples_fb_summer = get_success_examples(fb_summer, success_window_max = 14, success_window_min = 3)

length(success_examples_drs_fall)
length(success_examples_drs_summer)
length(success_examples_chng_fall)
length(success_examples_chng_summer)
length(success_examples_fb_fall)
length(success_examples_fb_summer)
length(success_examples_drs_all_time)
length(success_examples_drs_nov)

print(success_examples_drs_nov)

chng_success_intersect = intersect(success_examples_chng_fall, success_examples_chng_summer)
# print(chng_success_intersect)

drs_success_intersect = intersect(success_examples_drs_fall, success_examples_drs_summer)
print(drs_success_intersect)

fb_success_intersect = intersect(success_examples_fb_summer, success_examples_fb_fall)
# print(success_examples_fb_summer)
# print(fb_success_intersect)

# print(intersect(drs_success_intersect, chng_success_intersect))
# 
# plot_signals(chng_summer, "12115", smooth_and_show_increase_point=TRUE, "Chng COVID")
# plot_signals(drs_summer, "12115", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(chng_fall, "12115", smooth_and_show_increase_point=TRUE, "Chng COVID")
# plot_signals(drs_fall, "12115", smooth_and_show_increase_point=TRUE, "Drs Visits")
# 
# # 
# plot_signals(chng_summer, "48439", smooth_and_show_increase_point=TRUE, "Chng COVID")
# plot_signals(drs_summer, "48439", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(chng_fall, "48439", smooth_and_show_increase_point=TRUE, "Chng COVID")
# plot_signals(drs_fall, "48439", smooth_and_show_increase_point=TRUE, "Drs Visits")
# 
# 
# plot_signals(drs_fall, "12115", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_summer, "12115", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_fall, "17111", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_summer, "17111", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_fall, "48141", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_summer, "48141", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_fall, "48439", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_summer, "48439", smooth_and_show_increase_point=TRUE, "Drs Visits")

plot_signals(drs_summer, "17119", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_fall, "17119", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_nov, "17119", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_all_time, "22055", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_all_time, "42003", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_summer, "16001", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_fall, "16001", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_nov, "16001", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_summer, "31153", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_fall, "31153", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_nov, "31153", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_all_time, "22055", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_all_time, "42003", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_summer, "48469", smooth_and_show_increase_point=TRUE, "Drs Visits")
# plot_signals(drs_fall, "48469", smooth_and_show_increase_point=TRUE, "Drs Visits")
plot_signals(drs_nov, "48469", smooth_and_show_increase_point=TRUE, "Drs Visits")

```
```{r}
# Find mean and median of county total case count of the successful counties over all time
sum_list <- vector(mode = "list", length = length(drs_success_intersect))
for (i in 1:length(drs_visits_prepared_summer$cases)) {
  if (drs_visits_prepared_summer$cases[[i]]$geo_value %in% drs_success_intersect) {
    sum = sum(drs_visits_prepared_summer$cases[[i]]$value)
    sum_list[i] = sum
  }
}
print(sum_list[!sapply(sum_list,is.null)])
print(median(unlist(sum_list)))
print(mean(unlist(sum_list)))

```

```{r}
# Find mean and median of county total case count over all time
sum_list <- vector(mode = "list", length = length(drs_visits_prepared_summer$cases))
for (i in 1:length(drs_visits_prepared_summer$cases)) {
  sum = sum(drs_visits_prepared_fall$cases[[i]]$value)
  sum = sum + sum(drs_visits_prepared_summer$cases[[i]]$value)
  sum_list[i] = sum
}
print(median(unlist(sum_list)))
print(mean(unlist(sum_list)))
```
```{r}
get_leading_indicator_day_distribution<-function(success_examples, final_cases_indicator_list)
{
  county_names=unlist(lapply(final_cases_indicator_list, function(x) x$geo_value[1]))
  success_examples_data = final_cases_indicator_list[which(county_names %in% unlist(success_examples))]
  names(success_examples_data)<-unlist(lapply(success_examples_data, function(x) x$geo_value[1]))
  # print(names(success_examples_data))
  return(lapply(success_examples_data, function(x){
    as.integer(x$time_value[which(x$case_rise_point==1)]-x$time_value[which(x$indicator_rise_point==1)])
  }))
}

plot_distribution_freq = function(examples, signal_data) {
  aheads = get_leading_indicator_day_distribution(examples, signal_data)
  distribution = data.frame(leadingness=integer(), freq=integer())
  for (i in 1:length(aheads)) {
    for (j in 1:length(aheads[[i]])) {
      if (aheads[[i]][[j]] %in% distribution$leadingness) {
        distribution$freq[distribution$leadingness == aheads[[i]][[j]]] <- distribution$freq[distribution$leadingness == aheads[[i]][[j]]] + 1
      } else {
        distribution[nrow(distribution) + 1,] = c(aheads[[i]][[j]], 1)
      }
    }
  }
  ggplot(distribution, aes(leadingness, freq)) + 
    geom_bar(aes(fill =leadingness), stat = 'identity') +
    scale_x_continuous(breaks = c(2,3,4,5,6,7,8,9,10,11,12,13,14,15))
}
  
```

```{r}
# plot_signals(final_cases_indicator_list, success_examples[[33]], "Dr visits", smooth_and_show_increase_point = TRUE)
# plot_signals(final_cases_indicator_list, success_examples[[33]], "Dr visits", smooth_and_show_increase_point = FALSE)
# plot_signals(final_cases_indicator_list, success_examples[[1]], "Dr visits", smooth_and_show_increase_point = TRUE)
# plot_signals(final_cases_indicator_list, success_examples[[1]], "Dr visits", smooth_and_show_increase_point = FALSE)
# plot_signals(final_cases_indicator_list, success_examples[[10]], "Dr visits", smooth_and_show_increase_point = TRUE)
# plot_signals(final_cases_indicator_list, success_examples[[10]], "Dr visits", smooth_and_show_increase_point = FALSE)
# plot_signals(final_cases_indicator_list, success_examples[[20]], "Dr visits", smooth_and_show_increase_point = TRUE)
# plot_signals(final_cases_indicator_list, success_examples[[20]], "Dr visits", smooth_and_show_increase_point = FALSE)
# plot_signals(final_cases_indicator_list, success_examples[[40]], "Dr visits", smooth_and_show_increase_point = TRUE)
# plot_signals(final_cases_indicator_list, success_examples[[40]], "Dr visits", smooth_and_show_increase_point = FALSE)
# plot_signals(final_cases_indicator_list, success_examples[[45]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(chng_summer, success_examples_chng_summer[[45]], "Chng COVID", smooth_and_show_increase_point = FALSE)
plot_signals(chng_summer, success_examples_chng_summer[[45]], "Chng COVID", smooth_and_show_increase_point = TRUE)


```
```{r}
source("LeadingIndicatorTools.R")
recall = get_recall_strict(final_cases_indicator_list)
recall

precision = get_precision_strict(final_cases_indicator_list)
precision
```



```{r}
generate_competitors_get_scores<-function(final_cases_indicator_list)
{
  all_guessers=lapply(final_cases_indicator_list, function(x){
    random_guesser <- rbinom(nrow(x), 1, 0.5)
    case_first_deriv=get_signal_first_derivative(signal = x$case_value, bandwidth = 14)
    indicator_first_deriv=get_signal_first_derivative(signal = x$ind_value, bandwidth = 14)
    x$random_guesser=random_guesser
    x$case_first_deriv_guesser=ifelse(case_first_deriv > 0, 1, 0)
    x$indicator_first_deriv=ifelse(indicator_first_deriv > 0, 1, 0)
    x
  })
  return(all_guessers)
}

get_signal_first_derivative<-function(signal, bandwidth)
{
  smoothed_signal=sm(signal, bandwidth)
  tt = 1:length(signal)
  first_deriv = stats::splinefun(tt, smoothed_signal)(tt, 1)
  return(first_deriv)
}
```


```{r}

use_time_windows = function(competitors_df) {
  for (c in (1:length(competitors_df))) {
    for (i in (1:length(competitors_df[[c]]$time_value))) {
      if (competitors_df[[c]]$case_rise_point[[i]] == 1){
        for(j in (1:7-1)) {
         if (i-j > 0) {
           competitors_df[[c]]$case_rise_point[[i-j]] = 1
         }
        }
      }
    }
    i = length(competitors_df[[c]]$time_value)
    while(i > 0) {
      if (competitors_df[[c]]$indicator_rise_point[[i]] == 1){
          for(j in (1:6)) {
            if (i+j <= length(competitors_df[[c]]$time_value)) {
              competitors_df[[c]]$indicator_rise_point[[i+j]] = 1
            }
          }
      }
      i = i-1
    }
  }
  return (competitors_df)
}
```

```{r}

get_recall_and_precision = function(competitors, guesser) {
  true_positives = 0
  false_positives = 0
  true_negatives = 0
  false_negatives = 0
  for (c in (1:10)) {
    for (i in (1:length(competitors[[c]]$time_value))) {
      guesser_points = competitors[[c]][guesser]
      guesser_point = as.numeric(unlist(guesser_points))[[i]]
      if (competitors[[c]]$case_rise_point[[i]] == 1 && guesser_point == 1) {
        true_positives = true_positives + 1
      }
      if (competitors[[c]]$case_rise_point[[i]] == 1 && guesser_point == 0) {
        false_negatives = false_negatives + 1
      } 
      if (competitors[[c]]$case_rise_point[[i]] == 0 && guesser_point == 0) {
        true_negatives = true_negatives + 1
      } 
      if (competitors[[c]]$case_rise_point[[i]] == 0 && guesser_point == 1) {
        false_positives = false_positives + 1
      } 
    }
  }
  print(guesser)
  print("Recall: ")
  print(true_positives / (true_positives + false_positives))
  print("Precision ") 
  print(true_positives / (true_positives + false_negatives))
}
```

```{r}
print("Drs Visits SUMMER")
competitors_drs_summer = generate_competitors_get_scores(drs_summer)
competitors_drs_summer = use_time_windows(competitors_drs_summer)
get_recall_and_precision(competitors_drs_summer, "indicator_rise_point")
# print(competitors[100])
get_recall_and_precision(competitors_drs_summer, 'random_guesser')
get_recall_and_precision(competitors_drs_summer, 'case_first_deriv_guesser')

print("")
print("Drs Visits FALL")
competitors_drs_fall = generate_competitors_get_scores(drs_fall)
competitors_drs_fall = use_time_windows(competitors_drs_fall)
get_recall_and_precision(competitors_drs_fall, "indicator_rise_point")
# print(competitors[100])
get_recall_and_precision(competitors_drs_fall, 'random_guesser')
get_recall_and_precision(competitors_drs_fall, 'case_first_deriv_guesser')

```


```{r}
source("2_7_21_Update/LeadingIndicatorToolsVS_v2.R")
guessers=generate_competitors_get_scores(final_cases_indicator_list = drs_fall)
guessers[1]
# get_performances=get_county_level_precision_recall(final_cases_indicator_list = guessers, min_window = 3, max_window = 14)

# get_performances
```
