---
title: "R Notebook"
output: html_notebook
---

```{r}
source("LeadingIndicatorTools.R")
library(covidcast)
library(magrittr)
library(tidyverse)
library(assertthat)
library(lubridate)

prepared = get_and_parse_signals("2020-09-01", "2020-11-30", "doctor-visits", "smoothed_adj_cli", 2000, 80)
print(length(prepared$cases))

```

```{r}
final_cases_indicator_list = get_increase_points(prepared$cases, prepared$indicator)

print(final_cases_indicator_list[[1]])
print(final_cases_indicator_list[[50]])
print(final_cases_indicator_list[[100]])
print(final_cases_indicator_list[[150]])
print(final_cases_indicator_list[[442]])


```
```{r}
plot_signals(final_cases_indicator_list, "39011", smooth_and_show_increase_point=FALSE, "Dr visits")
plot_signals(final_cases_indicator_list, "39011", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "17007", smooth_and_show_increase_point=FALSE, "Dr visits")
plot_signals(final_cases_indicator_list, "17007", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "05119", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "06029", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "06067", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "06079", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "06097", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "12001", smooth_and_show_increase_point=TRUE, "Dr visits")
plot_signals(final_cases_indicator_list, "18163", smooth_and_show_increase_point=TRUE, "Dr visits")



```

```{r}
success_examples = get_success_examples(final_cases_indicator_list, 14)
length(success_examples)
```
```{r}
plot_signals(final_cases_indicator_list, success_examples[[33]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(final_cases_indicator_list, success_examples[[33]], "Dr visits", smooth_and_show_increase_point = FALSE)
plot_signals(final_cases_indicator_list, success_examples[[1]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(final_cases_indicator_list, success_examples[[1]], "Dr visits", smooth_and_show_increase_point = FALSE)
plot_signals(final_cases_indicator_list, success_examples[[10]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(final_cases_indicator_list, success_examples[[10]], "Dr visits", smooth_and_show_increase_point = FALSE)
plot_signals(final_cases_indicator_list, success_examples[[20]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(final_cases_indicator_list, success_examples[[20]], "Dr visits", smooth_and_show_increase_point = FALSE)
plot_signals(final_cases_indicator_list, success_examples[[40]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(final_cases_indicator_list, success_examples[[40]], "Dr visits", smooth_and_show_increase_point = FALSE)
plot_signals(final_cases_indicator_list, success_examples[[45]], "Dr visits", smooth_and_show_increase_point = TRUE)
plot_signals(final_cases_indicator_list, success_examples[[45]], "Dr visits", smooth_and_show_increase_point = FALSE)


```
```{r}
source("LeadingIndicatorTools.R")
recall = get_recall_strict(final_cases_indicator_list)
recall

precision = get_precision_strict(final_cases_indicator_list)
precision
```
